# Markdown example with knitr and googleVis
===========================================
This is a little Markdown example file.
Set the googleVis options first.
In this case change the behaviour of plot.gvis
```{r setOptions, message=FALSE}
library(googleVis)
op <- options(gvis.plot.tag='chart')
library(zoo)
load("ForumPosts.RData")
colnames(motion.data3)[1:4] <- c("Category","Date","Posts","Views")
levels(motion.data3$Category) <- c("Biology","Chemistry","Chemistry","Climate","CS","Engineering","General","Math",
                                   "Philosophy & Religion","Physics","Politics","Speculations","Staff")
motion.data3$Date <-as.POSIXlt(motion.data3$Date)$year + 1900
motion.data3 <- aggregate(formula=cbind(Views,Posts)~Category+Date,FUN=sum,data=motion.data3)
```
The following plot statements will automatically return the HTML
required for the 'knitted' output.
 
## Combo chart
```{r, echo=FALSE,results='asis'}
p <- gvisMotionChart(xvar="Views",yvar="Posts",data=motion.data3,timevar="Date",idvar="Category")
plot(p)
```